apiVersion: v1
kind: Template
labels:
  app: freelancer-service
metadata:
  name: freelancer-postgresql
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: freelancer-service
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 5432
      targetPort: 5432
    selector:
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: freelancer-service
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      recreateParams:
        post:
          execNewPod:
            command:
              - /bin/sh
              - -i
              - -c
              - sleep 10 && PGPASSWORD=$POSTGRESQL_PASSWORD psql -h $FREELANCER_POSTGRESQL_SERVICE_HOST -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c "$POSTGRESQL_INIT"
            containerName: ${APPLICATION_NAME}
            env:
            - name: POSTGRESQL_INIT
              value: CREATE TABLE users (freelancerid bigint NOT NULL, first_name character varying(255) COLLATE pg_catalog."default", last_name character varying(255) COLLATE pg_catalog."default", email character varying(255) COLLATE pg_catalog."default", CONSTRAINT users_pkey PRIMARY KEY (freelancerid));
                CREATE TABLE skill (id bigint NOT NULL , skill_name character(1) COLLATE pg_catalog."default", CONSTRAINT skill_pkey PRIMARY KEY (id));
                CREATE TABLE skill_user (freelancerid bigint NOT NULL, skill_id bigint NOT NULL, CONSTRAINT skill_user_pkey PRIMARY KEY (freelancerid, skill_id));
                ALTER TABLE skill_user OWNER to jboss;
                ALTER TABLE users OWNER to jboss;
                ALTER TABLE skill OWNER to jboss;
                INSERT into skill (id, skill_name) values (1, 'Java');
                INSERT into skill (id, skill_name) values (2, 'Thorntail');
                INSERT into skill (id, skill_name) values (3, 'Vert.x');
                INSERT into skill (id, skill_name) values (4, 'Spring Boot');
                INSERT into users (freelancerid, first_name, last_name, email) values (11, 'test11', 'test1', 'test1@gmail.com');
                INSERT into users (freelancerid, first_name, last_name, email) values (22, 'test22', 'test2', 'test2@gmail.com');
                INSERT into users (freelancerid, first_name, last_name, email) values (33, 'test33', 'test3', 'test3@gmail.com');
                INSERT into users (freelancerid, first_name, last_name, email) values (44, 'test44', 'test4', 'test4@gmail.com');
                INSERT into users (freelancerid, first_name, last_name, email) values (55, 'test45', 'test4', 'test4@gmail.com');
                INSERT into skill_user (freelancerid, skill_id) values (11,1);
                INSERT into skill_user (freelancerid, skill_id) values (11,2);
                INSERT into skill_user (freelancerid, skill_id) values (11,3);
                INSERT into skill_user (freelancerid, skill_id) values (22,1);
                INSERT into skill_user (freelancerid, skill_id) values (22,2);
                INSERT into skill_user (freelancerid, skill_id) values (33,1);
                INSERT into skill_user (freelancerid, skill_id) values (44,1);
                INSERT into skill_user (freelancerid, skill_id) values (44,3);
                INSERT into skill_user (freelancerid, skill_id) values (55,1);
                INSERT into skill_user (freelancerid, skill_id) values (55,4);
          failurePolicy: ignore
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: freelancer-service
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: POSTGRESQL_USER
            value: ${FREELANCER_DB_USERNAME}
          - name: POSTGRESQL_PASSWORD
            value: ${FREELANCER_DB_PASSWORD}
          - name: POSTGRESQL_DATABASE
            value: ${FREELANCER_DB_NAME}
          image: postgresql
          imagePullPolicy: IfNotPresent
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 5432
            protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: freelancer-postgresql-data
          livenessProbe:
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 10
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
        terminationGracePeriodSeconds: 60
        volumes:
        - name: freelancer-postgresql-data
          persistentVolumeClaim:
            claimName: freelancer-postgresql-pv
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: postgresql:latest
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: freelancer-service
    name: freelancer-postgresql-pv
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
parameters:
- description: Application name
  name: APPLICATION_NAME
  required: true
  value: freelancer-postgresql
- description: Freelancer Service database user name
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: FREELANCER_DB_USERNAME
  required: true
- description: Freelancer Service database user password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: FREELANCER_DB_PASSWORD
  required: true
- description: Freelancer Service database name
  name: FREELANCER_DB_NAME
  required: true
  value: freelancerdb